language: java
jdk:
  - openjdk8
os:
  - linux
sudo: false
install: true
notifications:
  on_success:
    - change
  on_failure:
    - change
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - .autoconf
    - $HOME/.m2  
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/    
script:
  - ./gradlew build --parallel
